{
 "title": "RHODA_Metrics_Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_id", "label": "Select the cluster ", "query": { "query": "dbaas_version_info" } }
  ]
 },
 "panels": [
  {
   "title": "Total Installation",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(dbaas_version_info)" }
   ]
  },
  {
   "title": "Clusters Information",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "dbaas_version_info" }
   ]
  },
  {
   "title": "Installations  status for $cluster_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "cluster_id"
  },
  {
   "title": "Platform Stack Installation Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "dbaas_platform_installation_status{cluster_id=`$cluster_id`}"
    }
   ]
  },
  {
   "title": "Total Count for  Cluster $cluster_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "cluster_id"
  },
  {
   "title": "Total Provider Account  Count",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dbaas_inventory_status_ready{cluster_id=~`$cluster_id`})"
    }
   ]
  },
  {
   "title": "Provider Accounts Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dbaas_inventory_status_ready{cluster_id=~`$cluster_id`}"
    }
   ]
  },
  {
   "title": "Total Connections Count ",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dbaas_connection_status_ready{cluster_id=~`$cluster_id`})"
    }
   ]
  },
  {
   "title": "Connections Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dbaas_connection_status_ready{cluster_id=~`$cluster_id`}"
    }
   ]
  },
  {
   "title": "Total Instances Count ",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dbaas_instance_status_ready{cluster_id=~`$cluster_id`})"
    }
   ]
  },
  {
   "title": "Instances Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dbaas_instance_status_ready{cluster_id=~`$cluster_id`}"
    }
   ]
  }
 ]
}