:_module-type: PROCEDURE

[id="find-your-amazon-rds-account-credentials_{context}"]

= Find your Amazon RDS account credentials

[role="_abstract"]
You need an Amazon Web Services (**AWS**) **Access key ID**, an **AWS Secret access key**, and know which **AWS Region** you are using to import an Amazon Relational Database Service (RDS) provider account for OpenShift Database Access.
If you lose your AWS Access key ID, and your AWS Secret access key, new ones must be created.

[NOTE]
====
Amazon only allows two secret access keys for each user.
You might need to deactivate unused keys, or delete lost keys before you can create a new access key.
====

[IMPORTANT]
====
You are limited to one Amazon RDS provider account per OpenShift cluster.
Using your AWS credentials on more than one OpenShift cluster breaks established connections on all OpenShift clusters, except for the last OpenShift cluster that established a connection.
====

IMPORTANT: OpenShift Database Access only supports RDS database **instance deployments**, and does not support database **cluster deployments**.

IMPORTANT: Database instances using a custom Oracle or custom SQL Server engine type are not supported.

.Prerequisites

* An Amazon Web Services link:https://portal.aws.amazon.com/billing/signup?nc2=h_ct&src=header_signup&redirect_url=https%3A%2F%2Faws.amazon.com%2Fregistration-confirmation#/start/email[(AWS) account name].

.Procedure

. Sign in to Amazon’s Identity and Access Management link:https://console.aws.amazon.com/[(IAM) console] with your AWS user account.

. From the IAM console home page, expand the **Access management** menu, and click **Users**.

. Select a user from the list.

. On the user’s summary page, select the **Security credentials** tab, and click the **Create access key** button.

. Copy the **AWS Access key ID**, and the **AWS Secret access key**.

////
[role="_additional-resources"]
.Additional resources

*
////
