:_module-type: PROCEDURE

[id="creating-an-azure-red-hat-openshift-cluster_{context}"]

= Creating an Azure Red Hat OpenShift cluster

[role="_abstract"]
You can manually create Red Hat OpenShift clusters running on Microsoft’s Azure cloud computing service.
Once an Azure Red Hat OpenShift (ARO) cluster is running you can register the ARO cluster with the link:https://console.redhat.com/[Red Hat Hybrid Cloud Console].

IMPORTANT: Currently, creating an Azure Red Hat OpenShift cluster is not supported by using the Red Hat Hybrid Cloud Console.

.Prerequisites

* Installation of the link:https://docs.microsoft.com/en-us/cli/azure/install-azure-cli[Azure client], version 2.6 or higher.
* A link:https://portal.azure.com/[Microsoft Azure] organizational or user account with an active subscription.
* Download a link:https://access.redhat.com/documentation/en-us/openshift_cluster_manager/2022/html/managing_clusters/assembly-managing-clusters#downloading_and_updating_pull_secrets[pull secret] for authentication to an OpenShift cluster.

.Procedure

. Login to the Microsoft Azure portal from the command-line client:
+
----
$ az login
----
+
[NOTE]
====
Running this command opens a web browser for you to finish the login process.
You can close the browser after you successfully logged in.
====

. Set the account subscription:
+
.Syntax
[source,subs="verbatim,quotes"]
----
az account set --subscription ‘_SUBSCRIPTION_NAME_’
----
+
.Example
----
$ az account set –-subscription ‘Example Sub’
----

. Register the Azure resources:
+
.Example
----
$ az provider register -n Microsoft.RedHatOpenShift --wait
$ az provider register -n Microsoft.Compute --wait
$ az provider register -n Microsoft.Storage --wait
----

. Create a resource group:
+
.Syntax
[source,subs="verbatim,quotes"]
----
az group create --name _RESOURCE_GROUP_ --location _LOCATION_
----
+
.Example
----
$ az group create --name rhoda-aro-gr --location eastus
----

. Create a virtual network:
+
.Syntax
[source,subs="verbatim,quotes"]
----
az network vnet create --resource-group _RESOURCE_GROUP_ \
--name aro-vnet \
--address-prefixes _IP_SUBNET_/_CIDR_
----
+
.Example
----
$ az network vnet create --resource-group rhoda-aro-gr \
--name aro-vnet \
--address-prefixes 10.0.0.0/22
----

. Create a subnet for the main node:
+
.Syntax
[source,subs="verbatim,quotes"]
----
az network vnet subnet create --resource-group _RESOURCE_GROUP_ \
--vnet-name aro-vnet \
--name main-subnet \
--address-prefixes _IP_SUBNET_/_CIDR_ \
--service-endpoints Microsoft.ContainerRegistry
----
+
.Example
----
$ az network vnet subnet create --resource-group rhoda-aro-gr \
--vnet-name aro-vnet \
--name main-subnet \
--address-prefixes 10.0.0.0/23 \
--service-endpoints Microsoft.ContainerRegistry
----

. Create a subnet for the worker node:
+
.Syntax
[source,subs="verbatim,quotes"]
----
az network vnet subnet create --resource-group _RESOURCE_GROUP_ \
--vnet-name aro-vnet \
--name worker-subnet \
--address-prefixes _IP_SUBNET_/_CIDR_ \
--service-endpoints Microsoft.ContainerRegistry
----
+
.Example
----
$ az network vnet subnet create --resource-group rhoda-aro-gr \
--vnet-name aro-vnet \
--name worker-subnet \
--address-prefixes 10.0.2.0/23 \
--service-endpoints Microsoft.ContainerRegistry
----

. Disable private endpoint policies for the main subnet:
+
.Syntax
[source,subs="verbatim,quotes"]
----
az network vnet subnet update --name main-subnet \
--resource-group _RESOURCE_GROUP_ \
--vnet-name aro-vnet \
--disable-private-link-service-network-policies true
----
+
.Example
----
$ az network vnet subnet update --name main-subnet \
--resource-group rhoda-aro-gr \
--vnet-name aro-vnet \
--disable-private-link-service-network-policies true
----

. Create the ARO cluster:
+
.Syntax
[source,subs="verbatim,quotes"]
----
az aro create --resource-group _RESOURCE_GROUP_ \
--name _CLUSTER_NAME_ \
--vnet aro-vnet \
--master-subnet main-subnet \
--worker-subnet worker-subnet \
--apiserver-visibility Public \
--ingress-visibility Public \
--pull-secret @_DOWNLOADED_PULL_SECRET_FILE_PWD_
----
+
.Example
----
$ az aro create --resource-group rhoda-aro-gr \
--name rhoda-aro-example \
--vnet aro-vnet \
--master-subnet main-subnet \
--worker-subnet worker-subnet \
--apiserver-visibility Public \
--ingress-visibility Public \
--pull-secret @pull-secret.txt
----
+
NOTE: The cluster creation process can take up to an hour to complete.

.Verification

. Once the cluster creation process finishes, copy the `kubeadmin` credentials, and the OpenShift console URL.

.. Find the `kubeadmin` credentials:
+
.Syntax
[source,subs="verbatim,quotes"]
----
az aro list-credentials --name _CLUSTER_NAME_ \
--resource-group _RESOURCE_GROUP_
----
+
.Example
----
$ az aro list-credentials --name rhoda-aro-example \
--resource-group rhoda-aro-gr

{
"kubeadminPassword": "AAFAA-Zk3aR-V46bu-A4F7D",
"kubeadminUsername": "kubeadmin"
}
----

.. Get the OpenShift console URL:
+
.Syntax
[source,subs="verbatim,quotes"]
----
az aro show --name _CLUSTER_NAME_ \
--resource-group _RESOURCE_GROUP_ \
--query "consoleProfile.url" -o tsv
----
+
.Example
----
$ az aro show --name rhoda-aro-example \
--resource-group rhoda-aro-gr \
--query "consoleProfile.url" -o tsv

https://console-openshift-console.apps.b879bjix.eastus.example.com/
----

. Use the `kubeadmin` credentials to login to the OpenShift console.

. From the OpenShift console home page, select the **Administrator** perspective, expand **Home** on the navigation menu, and click **Overview**.
+
Copy the **Cluster ID** value.
This value is used to register the ARO cluster with the Red Hat Hybrid Cloud Console.

////
[role="_additional-resources"]
.Additional resources

*
////
