:_module-type: PROCEDURE

[id="registering-an-azure-red-hat-openshift-cluster-with-the-red-hat-hybrid-cloud-console_{context}"]

= Registering an Azure Red Hat OpenShift cluster with the Red Hat Hybrid Cloud Console

[role="_abstract"]
You have to manually register Azure Red Hat OpenShift (ARO) clusters with the Red Hat Hybrid Cloud Console for them to start sending telemetry data about the ARO cluster.

.Prerequisites

* A running ARO cluster.
* Download a link:https://access.redhat.com/documentation/en-us/openshift_cluster_manager/2022/html/managing_clusters/assembly-managing-clusters#downloading_and_updating_pull_secrets[pull secret] for authentication to an OpenShift cluster, and the Red Hat Hybrid Cloud Console.
* A Red Hat user account for access to the Red Hat Hybrid Cloud Console.

.Procedure

. Log into OpenShift using the a command-line interface:
+
.Syntax
[source,subs="verbatim,quotes"]
----
oc login --token=_TOKEN_ --server=_SERVER_URL_AND_PORT_
----
+
.Example
----
$ oc login --token=sha256~ZvFDBvoIYAbVECixS4-WmkN4RfnNd8Neh3y1WuiFPXC --server=https://example.com:6443
----
+
[NOTE]
====
You can find your command-line login token and URL from the OpenShift console.
Once you log into the OpenShift console, click your user name, click **Copy login command**, login once again using your user name and password, then click **Display Token** to view the command.
====

. From the OpenShift host, get and encode the pull secret file:
+
.Example
----
$ oc get secrets pull-secret -n openshift-config \
-o template='{{index .data ".dockerconfigjson"}}' | \
base64 -d > pull-secret-post.json
----

. Open the downloaded pull secret file, and copy the whole `cloud.redhat.com` authorization entry.
+
.Copy Example
[source,subs="verbatim,quotes"]
----
"cloud.openshift.com":{
    "auth":"<_REDACTED_>",
    "email":"user@example.com"
},
----
+
Close the pull secret file.

. Open the `pull-secret-post.json` file, and paste the copied `cloud.redhat.com` authorization entry.
Close the pull secret file.

. Validate the JSON file:
+
.Example
----
$ cat pull-secret-post.json | jq
----

. Update the ARO cluster with the new pull secret file:
+
.Example
----
$ oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=./pull-secret-post.json
----
+
After a few minutes the ARO cluster appears in the Red Hat Hybrid Cloud Console.

.Verification

. Login to the link:https://console.redhat.com/[Red Hat Hybrid Cloud Console].

. Click **OpenShift**, then click **Cluster**.

. From the **Cluster** page, filter for the ARO cluster by its cluster ID.
The new ARO cluster is now in the cluster list.
+
NOTE: The default service-level agreement (SLA) is set to **Self-Support 60-day evaluation**.

. Optionally, you can change the default SLA:

.. Click the cluster ID.

.. Click the **Edit subscription settings** link within the warning message.

.. Select the appropriate SLA for your subscription, and click **Save**.

////
[role="_additional-resources"]
.Additional resources

*
////
