:_module-type: CONCEPT

[id="service-binding-libraries_{context}"]

= Service binding libraries

[role="_abstract"]
The Kubernetes service binding feature brings consistency to sharing secrets for connecting applications to external services, such as REST APIs, databases, and many other services.
OpenShift Database Access leverages the service binding feature to bring a low-touch administrative experience to provisioning and managing access to external database services.
The service binding feature enables developers to connect their applications to database services with a consistent and predictable experience.
Specifically, a service binding creates a volume on the application pod and organizes the information to make a connection to the database in a directory structure.
An environment variable exposes the volume mount point.
Developer frameworks, such as Quarkus, are service binding aware, and can automatically connect to a database by using this exposed workload information without needing to embed database connection information in the application source code.

Here are some application examples on how to use a service binding library:

* link:https://github.com/RHEcosystemAppEng/mongo-quickstart[Mongo Quarkus application]
* link:https://github.com/RHEcosystemAppEng/postgresql-orm-quickstart[Crunchy Postgres Quarkus application]
* link:https://github.com/myeung18/postgresql-orm-demo-app[CockroachDB Postgres Quarkus application]
* link:https://github.com/myeung18/cockroachdb-go-quickstart[CockroachDB Postgres Go application]
* link:https://github.com/RHODA-lab/rhoda-qa-python/blob/main/test-crunchy-postgres.py[Crunchy Postgres Python test program]
* link:https://github.com/RHODA-lab/rhoda-qa-python/blob/main/test-cockroachdb.py[CockroachDB Postgres Python test program]
* link:https://github.com/myeung18/spring-boot-dbaas-demo-apps[Spring Boot Fruit Shop application for MongoDB and Postgres]

[role="_additional-resources"]
.Additional resources

* See the link:https://github.com/servicebinding/spec#workload-projection[Kubernetes GitHub project] for more details on service bindings.
