:_module-type: PROCEDURE

[id="connecting-an-application-to-a-known-database-instance_{context}"]

= Connecting an application to a known database instance

[role="_abstract"]
This use case connects an application to a known database instance from a cloud-hosted database provider.

You can implement the OpenShift Database Access application programming interface (API) schemas in one of two ways:

* By using an in-line code block with the `oc apply` command, and the `EOF` descriptor.
* By writing a static YAML file for use with the `oc apply` command.

The examples in this procedure uses MongoDB Atlas as the cloud-hosted database provider.
The procedure gives a schema syntax example, followed by an implementation example that uses an in-line code block with the `oc apply` command.
You create the resource objects in this order: _DBaaSPolicy_, _Secret_, _DBaaSInventory_, _DBaaSConnection_, _ServiceBinding_.

.Prerequisites

* A running OpenShift Dedicated, Red Hat OpenShift on AWS (ROSA), or Azure Red Hat OpenShift (ARO) cluster.
* link:https://access.redhat.com/documentation/en-us/red_hat_openshift_database_access/1/html/quick_start_guide/installing-the-red-hat-openshift-database-access-add-on_rhoda-qsg[Installation] of the OpenShift Database Access add-on.
* User access to the command-line interface (CLI) for the OpenShift cluster.
* An existing application namespace.

.Procedure

. Log into OpenShift by using the command-line interface:
+
.Syntax
[source,subs="verbatim,quotes"]
----
oc login --token=_TOKEN_ --server=_SERVER_URL_AND_PORT_
----
+
.Example
----
$ oc login --token=sha256~ZvFDBvoIYAbVECixS4-WmkN4RfnNd8Neh3y1WuiFPXC --server=https://example.com:6443
----
+
[NOTE]
====
You can find your command-line login token and URL from the OpenShift console.
Log in to the OpenShift console.
Click your user name, and click **Copy login command**.
Offer your user name and password again, and click **Display Token** to view the command.
====

. You can use the default _DBaaSPolicy_ object in the `redhat-dbaas-operator` namespace, and modify it according to your needs.
Or, you can create a new _DBaaSPolicy_ object in the project namespace.
+
////
// 9.16.22 - Aron : Commenting out the syntax and example for creating a new DBaaSPolicy object, since most people will just update the default policy.

.Syntax
[source,subs="verbatim,quotes"]
----
apiVersion: dbaas.redhat.com/v1beta1
kind: DBaaSPolicy
metadata:
  name: cluster
  namespace: _ADMIN_NAMESPACE_ <1>
spec:
  connections:
    namespaces:
    - '*'
----
<1> The namespace where _DBaaSPolicy_ allows for the creation of a _DBaaSInventory_, and also has the Provider Account and secret information. The default namespace is `redhat-dbaas-operator`.
+
.Example
----
$ cat <<EOF | oc apply -f -
apiVersion: dbaas.redhat.com/v1beta1
kind: DBaaSPolicy
metadata:
  name: cluster
  namespace: redhat-dbaas-operator
spec:
  connections:
    namespaces:
    - '*'
EOF
----
////

. Create a _Secret_ object and apply it to the OpenShift cluster:
+
.Syntax
[source,subs="verbatim,quotes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: _WORKFLOW_NAME_ <1>
  namespace: _ADMIN_NAMESPACE_ <2>
data:
  orgId: _ORGANIZATION_ID_ <3>
  privateApiKey: _PRIVATE_KEY_ <4>
  publicApiKey: _PUBLIC_KEY_ <5>
type: Opaque
----
<1> The name of the workflow.
<2> The namespace where _DBaaSPolicy_ allows for the creation of a _DBaaSInventory_, and also has the provider account and secret information. The default namespace is `redhat-dbaas-operator`.
<3> The unique cloud-hosted database provider organizational identifier assigned to your account.
<4> The private API key. Key encoding must use `base64`.
<5> The public API key. Key encoding must use `base64`.
+
.Example
----
$ cat <<EOF | oc apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-atlas-user-secrets
  namespace: redhat-dbaas-operator
data:
  orgId: JjA4ZGY1ZTY1MmAxOTQ0MjkzZTg45DRh
  privateApiKey: PTAzOWQyOTMtNGJhMy01ZjdkLTk2ZWEtNWQ1MzNkYWQ1OTk7
  publicApiKey: tXpkaWl3aWw=
type: Opaque
EOF
----

. Create a _DBaaSInventory_ object and apply it to the OpenShift cluster:
+
.Syntax
[source,subs="verbatim,quotes"]
----
apiVersion: dbaas.redhat.com/v1beta1
kind: DBaaSInventory
metadata:
  labels:
    related-to: dbaas-operator
    type: dbaas-vendor-service
  name: _WORKFLOW_NAME_ <1>
  namespace: _ADMIN_NAMESPACE_ <2>
spec:
  credentialsRef:
    name: _SECRET_NAME_ <3>
  providerRef:
    name: _PROVIDER_TYPE_ <4>
----
<1> The name of the provider account workflow.
<2> The namespace where _DBaaSPolicy_ allows for the creation of a _DBaaSInventory_, and also has the Provider Account and secret information. The default namespace is `redhat-dbaas-operator`.
<3> The name of the secret object.
<4> The cloud-hosted database provider, for example, `mongodb-atlas-registration`, `cockroachdb-cloud-registration`, or `crunchy-bridge-registration`.
+
.Example
----
$ cat <<EOF | oc apply -f -
apiVersion: dbaas.redhat.com/v1beta1
kind: DBaaSInventory
metadata:
  labels:
    related-to: dbaas-operator
    type: dbaas-vendor-service
  name: mongodb-atlas-provider-account
  namespace: redhat-dbaas-operator
spec:
  credentialsRef:
    name: mongodb-atlas-user-secrets
  providerRef:
    name: mongodb-atlas-registration
EOF
----

. Create a _DBaaSConnection_ object and apply it to the OpenShift cluster:
+
.Syntax
[source,subs="verbatim,quotes"]
----
apiVersion: dbaas.redhat.com/v1beta1
kind: DBaaSConnection
metadata:
  name: _CONNECTION_NAME_ <1>
  namespace: _APP_NAMESPACE_ <2>
spec:
  inventoryRef:
    name: _INVENTORY_NAME_ <3>
    namespace: _NAMESPACE_ <4>
  databaseServiceID: _INSTANCE_ID_ <5>
----
<1> The name of the connection object.
<2> The name of the application deployment namespace.
<3> The name of the provider account inventory.
<4> The namespace where _DBaaSPolicy_ allows for the creation of a _DBaaSInventory_, and also has the Provider Account and secret information. The default namespace is `redhat-dbaas-operator`.
<5> The database instance unique ID.
+
.Example
----
$ cat <<EOF | oc apply -f -
apiVersion: dbaas.redhat.com/v1beta1
kind: DBaaSConnection
metadata:
  name: mongodb-atlas-connection
  namespace: my-app-example
spec:
  inventoryRef:
    name: mongodb-atlas-provider-account
    namespace: redhat-dbaas-operator
  databaseServiceID: 1671a1f0-5674-48d8-a16b-d2f2fcc6ff45f
EOF
----

. Create a _ServiceBinding_ object and apply it to the OpenShift cluster:
+
.Syntax
[source,subs="verbatim,quotes"]
----
apiVersion:  binding.operators.coreos.com/v1alpha1
kind:        ServiceBinding
metadata:
  name:      _BINDING_NAME_ <1>
  namespace: _APP_NAMESPACE_ <2>
spec:
  application:
    group:                   apps
    name:                    _APP_DEPLOYMENT_ <3>
    resource:                deployments
    version:                 v1
  bindAsFiles:             true
  detectBindingResources:  true
  services:
  - group:    dbaas.redhat.com
    kind:     DBaaSConnection
    name:     _CONNECTION_NAME_ <4>
    version:  v1beta1
----
<1> The name of the service binding object.
<2> The name of the application deployment namespace.
<3> The name for the connecting application's Kubernetes deployment.
<4> The name of the DBaaS connection object.
+
.Example
----
$ cat <<EOF | oc apply -f -
apiVersion:  binding.operators.coreos.com/v1alpha1
kind:        ServiceBinding
metadata:
  name:      mongodb-atlas-service-binder
  namespace: my-app-example
spec:
  application:
    group:                   apps
    name:                    my-app
    resource:                deployments
    version:                 v1
  bindAsFiles:             true
  detectBindingResources:  true
  services:
  - group:    dbaas.redhat.com
    kind:     DBaaSConnection
    name:     mongodb-atlas-connection
    version:  v1beta1
EOF
----

[role="_additional-resources"]
.Additional resources

* See the Red Hat OpenShift Database Access link:https://access.redhat.com/documentation/en-us/red_hat_openshift_database_access/2022-q4/html-single/reference_guide/index#openshift-database-access-provider-account-policies-and-user-personas_rhoda-ref[_Reference Guide_] for more information about policies and personas.
