:_module-type: PROCEDURE

[id="provisioning-a-new-free-trial-database-and-connecting-an-application-to-it_{context}"]

= Provisioning a new free trial database and connecting an application to it

[role="_abstract"]
This use case provisions a new free trial database and connects an application to the trial database.

IMPORTANT: Red Hat OpenShift Database Access currently only supports provisioning trial database instances.

You can implement the OpenShift Database Access application programming interface (API) schemas in one of two ways:

* By using in-line code with the `oc apply` command, and the `EOF` descriptor.
* By writing a static YAML file for use with the `oc apply` command.

The examples in this procedure uses MongoDB Atlas as the cloud-hosted database provider.
The procedure gives a schema syntax example, followed by an implementation example that uses an in-line code block with the `oc apply` command.
You create the resource objects in this order: _DBaaSInstance_, _DBaaSConnection_, _ServiceBinding_.

.Prerequisites

* A running OpenShift Dedicated, Red Hat OpenShift on AWS (ROSA), or Azure Red Hat OpenShift (ARO) cluster.
* link:https://access.redhat.com/documentation/en-us/red_hat_openshift_database_access/1/html/quick_start_guide/installing-the-red-hat-openshift-database-access-add-on_rhoda-qsg[Installation] of the OpenShift Database Access add-on.
* User access to the command-line interface (CLI) for the OpenShift cluster.
* An existing application namespace.

.Procedure

. Log into OpenShift by using the command-line interface:
+
.Syntax
[source,subs="verbatim,quotes"]
----
oc login --token=_TOKEN_ --server=_SERVER_URL_AND_PORT_
----
+
.Example
----
$ oc login --token=sha256~ZvFDBvoIYAbVECixS4-WmkN4RfnNd8Neh3y1WuiFPXC --server=https://example.com:6443
----
+
[NOTE]
====
You can find your command-line login token and URL from the OpenShift console.
Log in to the OpenShift console.
Click your user name, and click **Copy login command**.
Offer your user name and password again, and click **Display Token** to view the command.
====

. Create a _DBaaSInstance_ object to provision the new database instance and apply it to the OpenShift cluster:
+
.Syntax
[source,subs="verbatim,quotes"]
----
apiVersion: dbaas.redhat.com/v1beta1
kind: DBaaSInstance
metadata:
  name: _DB_INSTANCE_NAME_ <1>
  namespace: _APP_NAMESPACE_ <2>
spec:
  inventoryRef:
    name: _INVENTORY_NAME_ <3>
    namespace: _PA_NAMESPACE_ <4>
  cloudProvider: _DB_PROVIDER_ <5>
  cloudRegion: _REGION_ID_ <6>
  name: _DB_INSTANCE_NAME_
  otherInstanceParams:
    projectName: _MONGODB_ATLAS_PROJECT_NAME_ <7>
----
<1> The name of the database instance.
<2> The name of the application deployment namespace.
<3> The name of the provider account inventory.
<4> The namespace where _DBaaSPolicy_ allows for the creation of a _DBaaSInventory_, and also has the provider account and secret information. The default namespace is `redhat-dbaas-operator`.
<5> The cloud-hosted database provider.
<6> The deployment region for the cloud-hosted database provider.
<7> The project name for MongoDB Atlas.
+
.Example
----
$ cat <<EOF | oc apply -f -
apiVersion: dbaas.redhat.com/v1beta1
kind: DBaaSInstance
metadata:
  name: mongodb-atlas-instance 
  namespace: my-app-example
spec:
  inventoryRef:
    name: mongodb-atlas-provider-account
    namespace: redhat-dbaas-operator
  cloudProvider: aws
  cloudRegion: us-east-1
  name: mongodb-atlas-instance
  otherInstanceParams:
    projectName: mongodb-project
EOF
----
+
////
// 9/20/22 - Aron : Removing this step. Jian updated the use case to use the "instanceRef" instead of "instanceID".
// https://gist.github.com/jianrongzhang89/5759963b96326aa7be33b2f2d425c146/revisions
. Monitor the _DBaaSInventory_ custom resource (CR) status to find the new `instanceID`.
Use the `instanceID` value for the next step.
+
.Example
----
status:
  conditions:
  - lastTransitionTime: "2022-08-21T14:18:10Z"
    message: ""
    reason: Ready
    status: "True"
    type: ProvisionReady
  - lastTransitionTime: "2022-08-29T17:43:57Z"
    message: Provider Custom Resource status sync completed
    reason: Ready
    status: "True"
    type: InstanceReady
  instanceID: 62d95f4f02ea7712838c145a <1>
  instanceInfo:
    connectionStringsStandardSrv: mongodb+srv://example.k3fp7.mongodb.net
    instanceSizeName: M0
    projectID: 62d95f495114c74c3286b717
    projectName: mongodb-project
    providerName: AWS
    regionName: US_EAST_1
  phase: Ready
----
<1> The new database instance ID.
////

. Create a _DBaaSConnection_ object and apply it to the OpenShift cluster:
+
.Syntax
[source,subs="verbatim,quotes"]
----
apiVersion: dbaas.redhat.com/v1beta1
kind: DBaaSConnection
metadata:
  name: _CONNECTION_NAME_ <1>
  namespace: _APP_NAMESPACE_ <2>
spec:
  inventoryRef:
    name: _INVENTORY_NAME_ <3>
    namespace: _NAMESPACE_ <4>
  databaseServiceID: _INSTANCE_ID_ <5>
----
<1> The name of the connection object.
<2> The name of the application deployment namespace.
<3> The name of the provider account inventory.
<4> The namespace where _DBaaSPolicy_ allows for the creation of a _DBaaSInventory_, and also has the Provider Account and secret information. The default namespace is `redhat-dbaas-operator`.
<5> The database instance unique ID.
+
.Example
----
$ cat <<EOF | oc apply -f -
apiVersion: dbaas.redhat.com/v1beta1
kind: DBaaSConnection
metadata:
  name: mongodb-atlas-connection
  namespace: my-app-example
spec:
  inventoryRef:
    name: mongodb-atlas-provider-account
    namespace: redhat-dbaas-operator
  databaseServiceID: 1671a1f0-5674-48d8-a16b-d2f2fcc6ff45f
EOF
----

. Create a _ServiceBinding_ object and apply it to the OpenShift cluster:
+
.Syntax
[source,subs="verbatim,quotes"]
----
apiVersion:  binding.operators.coreos.com/v1alpha1
kind:        ServiceBinding
metadata:
  name:      _BINDING_NAME_ <1>
  namespace: _APP_NAMESPACE_ <2>
spec:
  application:
    group:                   apps
    name:                    _APP_DEPLOYMENT_ <3>
    resource:                deployments
    version:                 v1
  bindAsFiles:             true
  detectBindingResources:  true
  services:
  - group:    dbaas.redhat.com
    kind:     DBaaSConnection
    name:     _CONNECTION_NAME_ <4>
    version:  v1beta1
----
<1> The name of the service binding object.
<2> The name of the application deployment namespace.
<3> The name for the connecting application's Kubernetes deployment.
<4> The name of the DBaaS connection object.
+
.Example
----
$ cat <<EOF | oc apply -f -
apiVersion:  binding.operators.coreos.com/v1alpha1
kind:        ServiceBinding
metadata:
  name:      mongodb-atlas-service-binder
  namespace: my-app-example
spec:
  application:
    group:                   apps
    name:                    my-app
    resource:                deployments
    version:                 v1
  bindAsFiles:             true
  detectBindingResources:  true
  services:
  - group:    dbaas.redhat.com
    kind:     DBaaSConnection
    name:     mongodb-atlas-connection
    version:  v1beta1
EOF
----

[role="_additional-resources"]
.Additional resources

* See the Red Hat OpenShift Database Access link:https://access.redhat.com/documentation/en-us/red_hat_openshift_database_access/2022-q4/html-single/reference_guide/index#openshift-database-access-provider-account-policies-and-user-personas_rhoda-ref[_Reference Guide_] for more information about policies and personas.
