:_module-type: PROCEDURE

[id="deleting-a-database-provider-account_{context}"]

= Deleting a database provider account

[role="_abstract"]
Rather than directly editing your cloud-hosted database provider account information, Red Hat recommends you delete the provider account, and recreate a new one.

.Procedure

. Log into the OpenShift console.

. Select the **Administrator** perspective from the navigation menu.

. Expand the **Operators** navigation menu, and click **Installed Operators**.

. Click **OpenShift Database Access Operator** from the list of installed operators.

. Select **Provider Account**.

. Click the vertical ellipsis for the database provider account you want to delete, and click on **Delete DBaaSInventory**.

. A dialog box appears to confirm the deletion, click **Delete**.

. After deleting the database provider account, you can recreate the database provider account by clicking **Create DBaaSInventory**.

////
[role="_additional-resources"]
.Additional resources
////
