// The main assembly for Red Hat OpenShift Database Access (RHODA) Reference Guide

:imagesdir: images
:context: rhoda-ref
//:rhoda-prod-doc-url: https://access.redhat.com/documentation/en-us/red_hat_openshift_database_access/1/html/quick_start_guide/index

// Book Title
= Reference Guide

[IMPORTANT]
====
The Red Hat OpenShift Database Access is a Service Preview release add-on that enables:

* Easy consumption of database-as-a-service (DBaaS) offerings from partners including MongoDB Atlas, Crunchy Bridge, CockroachDB, and Amazon's Relational Database Services (RDS) directly from managed OpenShift clusters.
* Easy management, monitoring, and control by administrators of cloud-hosted DBaaS including consumption, usage, and status.

Red Hat OpenShift Database Access (OpenShift Database Access) is a Service Preview release.
A Service Preview release has features that are early in development.
Service Preview releases are not production ready and might have features and functionality that are not fully tested.
Red Hat advises you not to use OpenShift Database Access for production or business-critical workloads.

To give feedback or inform our engineering team of any technical issues with OpenShift Database Access, please use rhoda-requests@redhat.com.
====

// Deleting a provider account
include::modules/proc_deleting-a-database-provider-account_en-us.adoc[leveloffset=+1]

// Service binding libraries
include::modules/con_service-binding-libraries_en-us.adoc[leveloffset=+1]

// Integrating OpenShift Database Access with a Jupyter Notebook
include::modules/proc_integrating-openshift-database-access-with-a-jupyter-notebook_en-us.adoc[leveloffset=+1]

// Provider Account policies and user personas
include::modules/con_openshift-database-access-provider-account-policies-and-user-personas_en-us.adoc[leveloffset=+1]

// RHODA APIs
include::assembly_openshift-database-access-api-examples-and-schemas_en-us.adoc[leveloffset=+1]

// How to give feedback on Red Hat documentation
[appendix]
include::modules/proc_providing-feedback-on-red-hat-documentation_us-en.adoc[leveloffset=+1]