{
 "title": "Test-DBaaS_Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Crunchy Bridge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dbaas_platform_status{platform=\"crunchy-bridge\"}"
    }
   ]
  },
  {
   "title": "Mongodb Atlas",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dbaas_platform_status{platform=\"mongodb-atlas\"}"
    }
   ]
  },
  {
   "title": "DBaas Plugin",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dbaas_platform_status{platform=\"dbaas-dynamic-plugin\"}"
    }
   ]
  },
  {
   "title": "Console Telemetry Plugin",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dbaas_platform_status{platform=\"console-telemetry-plugin\"}"
    }
   ]
  },
  {
   "title": "Service Binding",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dbaas_platform_status{platform=\"service-binding\"}"
    }
   ]
  },
  {
   "title": "DBaaS Inventories",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max by (instance_name,instance_type,provider_name,result,message) (dbaas_request_duration_seconds_count{instance_type=\"DBaaSInventory\" })"
    }
   ]
  },
  {
   "title": "DBaaS Connections",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "max by (instance_name,result,instance_type,provider_name,message) (dbaas_request_duration_seconds_count{instance_type=\"DBaaSConnection\" })"
    }
   ]
  },
  {
   "title": "Crunchy Bridge Inventories",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count (sum without(pod,prometheus_replica) (dbaas_request_duration_seconds_sum{instance_type=\"DBaaSInventory\",provider_name=\"Red Hat DBaaS / Crunchy Bridge\" , outcome=\"success\"}))"
    }
   ]
  },
  {
   "title": "MongoDB Inventories",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (sum without(pod,prometheus_replica) (dbaas_request_duration_seconds_sum{instance_type=\"DBaaSInventory\",provider_name=\"Red Hat DBaaS / MongoDB Atlas\", outcome=\"success\"}))"
    }
   ]
  },
  {
   "title": "Crunchy Bridge Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (sum without(pod,prometheus_replica) (dbaas_request_duration_seconds_sum{instance_type=\"DBaaSConnection\",provider_name=\"Red Hat DBaaS / Crunchy Bridge\" ,outcome=\"success\"}))"
    }
   ]
  },
  {
   "title": "MongoDB Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (sum without(pod,prometheus_replica) (dbaas_request_duration_seconds_sum{instance_type=\"DBaaSConnection\",provider_name=\"Red Hat DBaaS / MongoDB Atlas\" ,outcome=\"success\"}))"
    }
   ]
  }
 ]
}