apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  managedFields:
  name: atlasaccounts.dbaas.redhat.com
  resourceVersion: "532345702"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/dbaasinventories.dbaas.redhat.com
  uid: b09bc4c3-3006-413c-92d4-b1558c5f0789
spec:
  conversion:
    strategy: None
  group: dbaas.redhat.com
  names:
    kind: AtlasAccount
    listKind: AtlasAccountList
    plural: atlasaccounts
    singular: atlasaccount
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: AtlasAccount is the Schema for the dbaasinventory API for MongoDB Atlas
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: DBaaSInventorySpec defines the desired state of DBaaSInventory
              properties:
                credentialsRef:
                  description: The secret storing the vendor-specific connection credentials to use with the API endpoint. The secret may be placed in a separate namespace to control access.
                  properties:
                    name:
                      description: The name for object of known type
                      type: string
                    namespace:
                      description: The namespace where object of known type is store
                      type: string
                  type: object
                provider:
                  description: Provider is the name of the database provider that we wish to connect with
                  properties:
                    name:
                      type: string
                  required:
                    - name
                  type: object
              required:
                - credentialsRef
                - provider
              type: object
            status:
              description: DBaaSInventoryStatus defines the observed state of DBaaSInventory
              properties:
                conditions:
                  items:
                    description: "Condition contains details for one aspect of the current state of this API Resource. --- This struct is intended for direct use as an array at the field path .status.conditions.  For example, type FooStatus struct{     // Represents the observations of a foo's current state.     // Known .status.conditions.type are: \"Available\", \"Progressing\", and \"Degraded\"     // +patchMergeKey=type     // +patchStrategy=merge     // +listType=map     // +listMapKey=type     Conditions []metav1.Condition `json:\"conditions,omitempty\" patchStrategy:\"merge\" patchMergeKey:\"type\" protobuf:\"bytes,1,rep,name=conditions\"` \n     // other fields }"
                    properties:
                      lastTransitionTime:
                        description: lastTransitionTime is the last time the condition transitioned from one status to another. This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                        format: date-time
                        type: string
                      message:
                        description: message is a human readable message indicating details about the transition. This may be an empty string.
                        maxLength: 32768
                        type: string
                      observedGeneration:
                        description: observedGeneration represents the .metadata.generation that the condition was set based upon. For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date with respect to the current state of the instance.
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        description: reason contains a programmatic identifier indicating the reason for the condition's last transition. Producers of specific condition types may define expected values and meanings for this field, and whether the values are considered a guaranteed API. The value should be a CamelCase string. This field may not be empty.
                        maxLength: 1024
                        minLength: 1
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                        type: string
                      status:
                        description: status of the condition, one of True, False, Unknown.
                        enum:
                          - "True"
                          - "False"
                          - Unknown
                        type: string
                      type:
                        description: type of condition in CamelCase or in foo.example.com/CamelCase. --- Many .condition.type values are consistent across resources like Available, but because arbitrary conditions can be useful (see .node.status.conditions), the ability to deconflict is important. The regex it matches is (dns1123SubdomainFmt/)?(qualifiedNameFmt)
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                        type: string
                    required:
                      - lastTransitionTime
                      - message
                      - reason
                      - status
                      - type
                    type: object
                  type: array
                instances:
                  description: A list of instances returned from querying the DB provider
                  items:
                    properties:
                      extraInfo:
                        additionalProperties:
                          type: string
                        description: Any other provider-specific information related to this instance
                        type: object
                      instanceID:
                        description: The ID for this instance in the database service
                        type: string
                      name:
                        description: The name of this instance in the database service
                        type: string
                    required:
                      - instanceID
                    type: object
                  type: array
                type:
                  description: E.g., MongoDB, Postgres
                  type: string
              required:
                - type
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
