//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialField) DeepCopyInto(out *CredentialField) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialField.
func (in *CredentialField) DeepCopy() *CredentialField {
	if in == nil {
		return nil
	}
	out := new(CredentialField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSConnection) DeepCopyInto(out *DBaaSConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSConnection.
func (in *DBaaSConnection) DeepCopy() *DBaaSConnection {
	if in == nil {
		return nil
	}
	out := new(DBaaSConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBaaSConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSConnectionList) DeepCopyInto(out *DBaaSConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DBaaSConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSConnectionList.
func (in *DBaaSConnectionList) DeepCopy() *DBaaSConnectionList {
	if in == nil {
		return nil
	}
	out := new(DBaaSConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBaaSConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSConnectionSpec) DeepCopyInto(out *DBaaSConnectionSpec) {
	*out = *in
	out.InventoryRef = in.InventoryRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSConnectionSpec.
func (in *DBaaSConnectionSpec) DeepCopy() *DBaaSConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(DBaaSConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSConnectionStatus) DeepCopyInto(out *DBaaSConnectionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.ConnectionInfoRef != nil {
		in, out := &in.ConnectionInfoRef, &out.ConnectionInfoRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSConnectionStatus.
func (in *DBaaSConnectionStatus) DeepCopy() *DBaaSConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(DBaaSConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSInstance) DeepCopyInto(out *DBaaSInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSInstance.
func (in *DBaaSInstance) DeepCopy() *DBaaSInstance {
	if in == nil {
		return nil
	}
	out := new(DBaaSInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBaaSInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSInstanceList) DeepCopyInto(out *DBaaSInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DBaaSInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSInstanceList.
func (in *DBaaSInstanceList) DeepCopy() *DBaaSInstanceList {
	if in == nil {
		return nil
	}
	out := new(DBaaSInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBaaSInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSInstanceSpec) DeepCopyInto(out *DBaaSInstanceSpec) {
	*out = *in
	out.InventoryRef = in.InventoryRef
	if in.OtherInstanceParams != nil {
		in, out := &in.OtherInstanceParams, &out.OtherInstanceParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSInstanceSpec.
func (in *DBaaSInstanceSpec) DeepCopy() *DBaaSInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(DBaaSInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSInstanceStatus) DeepCopyInto(out *DBaaSInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InstanceInfo != nil {
		in, out := &in.InstanceInfo, &out.InstanceInfo
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSInstanceStatus.
func (in *DBaaSInstanceStatus) DeepCopy() *DBaaSInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(DBaaSInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSInventory) DeepCopyInto(out *DBaaSInventory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSInventory.
func (in *DBaaSInventory) DeepCopy() *DBaaSInventory {
	if in == nil {
		return nil
	}
	out := new(DBaaSInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBaaSInventory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSInventoryList) DeepCopyInto(out *DBaaSInventoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DBaaSInventory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSInventoryList.
func (in *DBaaSInventoryList) DeepCopy() *DBaaSInventoryList {
	if in == nil {
		return nil
	}
	out := new(DBaaSInventoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBaaSInventoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSInventorySpec) DeepCopyInto(out *DBaaSInventorySpec) {
	*out = *in
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(NamespacedName)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSInventorySpec.
func (in *DBaaSInventorySpec) DeepCopy() *DBaaSInventorySpec {
	if in == nil {
		return nil
	}
	out := new(DBaaSInventorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSInventoryStatus) DeepCopyInto(out *DBaaSInventoryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]Instance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSInventoryStatus.
func (in *DBaaSInventoryStatus) DeepCopy() *DBaaSInventoryStatus {
	if in == nil {
		return nil
	}
	out := new(DBaaSInventoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSOperatorInventorySpec) DeepCopyInto(out *DBaaSOperatorInventorySpec) {
	*out = *in
	out.ProviderRef = in.ProviderRef
	in.Authz.DeepCopyInto(&out.Authz)
	if in.ConnectionNamespaces != nil {
		in, out := &in.ConnectionNamespaces, &out.ConnectionNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.DBaaSInventorySpec.DeepCopyInto(&out.DBaaSInventorySpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSOperatorInventorySpec.
func (in *DBaaSOperatorInventorySpec) DeepCopy() *DBaaSOperatorInventorySpec {
	if in == nil {
		return nil
	}
	out := new(DBaaSOperatorInventorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSPlatform) DeepCopyInto(out *DBaaSPlatform) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSPlatform.
func (in *DBaaSPlatform) DeepCopy() *DBaaSPlatform {
	if in == nil {
		return nil
	}
	out := new(DBaaSPlatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBaaSPlatform) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSPlatformList) DeepCopyInto(out *DBaaSPlatformList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DBaaSPlatform, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSPlatformList.
func (in *DBaaSPlatformList) DeepCopy() *DBaaSPlatformList {
	if in == nil {
		return nil
	}
	out := new(DBaaSPlatformList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBaaSPlatformList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSPlatformSpec) DeepCopyInto(out *DBaaSPlatformSpec) {
	*out = *in
	if in.SyncPeriod != nil {
		in, out := &in.SyncPeriod, &out.SyncPeriod
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSPlatformSpec.
func (in *DBaaSPlatformSpec) DeepCopy() *DBaaSPlatformSpec {
	if in == nil {
		return nil
	}
	out := new(DBaaSPlatformSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSPlatformStatus) DeepCopyInto(out *DBaaSPlatformStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSPlatformStatus.
func (in *DBaaSPlatformStatus) DeepCopy() *DBaaSPlatformStatus {
	if in == nil {
		return nil
	}
	out := new(DBaaSPlatformStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSProvider) DeepCopyInto(out *DBaaSProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSProvider.
func (in *DBaaSProvider) DeepCopy() *DBaaSProvider {
	if in == nil {
		return nil
	}
	out := new(DBaaSProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBaaSProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSProviderConnection) DeepCopyInto(out *DBaaSProviderConnection) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSProviderConnection.
func (in *DBaaSProviderConnection) DeepCopy() *DBaaSProviderConnection {
	if in == nil {
		return nil
	}
	out := new(DBaaSProviderConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSProviderInstance) DeepCopyInto(out *DBaaSProviderInstance) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSProviderInstance.
func (in *DBaaSProviderInstance) DeepCopy() *DBaaSProviderInstance {
	if in == nil {
		return nil
	}
	out := new(DBaaSProviderInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSProviderInventory) DeepCopyInto(out *DBaaSProviderInventory) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSProviderInventory.
func (in *DBaaSProviderInventory) DeepCopy() *DBaaSProviderInventory {
	if in == nil {
		return nil
	}
	out := new(DBaaSProviderInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSProviderList) DeepCopyInto(out *DBaaSProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DBaaSProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSProviderList.
func (in *DBaaSProviderList) DeepCopy() *DBaaSProviderList {
	if in == nil {
		return nil
	}
	out := new(DBaaSProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBaaSProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSProviderSpec) DeepCopyInto(out *DBaaSProviderSpec) {
	*out = *in
	out.Provider = in.Provider
	if in.CredentialFields != nil {
		in, out := &in.CredentialFields, &out.CredentialFields
		*out = make([]CredentialField, len(*in))
		copy(*out, *in)
	}
	if in.InstanceParameterSpecs != nil {
		in, out := &in.InstanceParameterSpecs, &out.InstanceParameterSpecs
		*out = make([]InstanceParameterSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSProviderSpec.
func (in *DBaaSProviderSpec) DeepCopy() *DBaaSProviderSpec {
	if in == nil {
		return nil
	}
	out := new(DBaaSProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSProviderStatus) DeepCopyInto(out *DBaaSProviderStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSProviderStatus.
func (in *DBaaSProviderStatus) DeepCopy() *DBaaSProviderStatus {
	if in == nil {
		return nil
	}
	out := new(DBaaSProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSTenant) DeepCopyInto(out *DBaaSTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSTenant.
func (in *DBaaSTenant) DeepCopy() *DBaaSTenant {
	if in == nil {
		return nil
	}
	out := new(DBaaSTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBaaSTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSTenantList) DeepCopyInto(out *DBaaSTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DBaaSTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSTenantList.
func (in *DBaaSTenantList) DeepCopy() *DBaaSTenantList {
	if in == nil {
		return nil
	}
	out := new(DBaaSTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBaaSTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSTenantSpec) DeepCopyInto(out *DBaaSTenantSpec) {
	*out = *in
	in.Authz.DeepCopyInto(&out.Authz)
	if in.ConnectionNamespaces != nil {
		in, out := &in.ConnectionNamespaces, &out.ConnectionNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSTenantSpec.
func (in *DBaaSTenantSpec) DeepCopy() *DBaaSTenantSpec {
	if in == nil {
		return nil
	}
	out := new(DBaaSTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaaSTenantStatus) DeepCopyInto(out *DBaaSTenantStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaaSTenantStatus.
func (in *DBaaSTenantStatus) DeepCopy() *DBaaSTenantStatus {
	if in == nil {
		return nil
	}
	out := new(DBaaSTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBaasUsersGroups) DeepCopyInto(out *DBaasUsersGroups) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBaasUsersGroups.
func (in *DBaasUsersGroups) DeepCopy() *DBaasUsersGroups {
	if in == nil {
		return nil
	}
	out := new(DBaasUsersGroups)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseProvider) DeepCopyInto(out *DatabaseProvider) {
	*out = *in
	out.Icon = in.Icon
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseProvider.
func (in *DatabaseProvider) DeepCopy() *DatabaseProvider {
	if in == nil {
		return nil
	}
	out := new(DatabaseProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance) DeepCopyInto(out *Instance) {
	*out = *in
	if in.InstanceInfo != nil {
		in, out := &in.InstanceInfo, &out.InstanceInfo
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance.
func (in *Instance) DeepCopy() *Instance {
	if in == nil {
		return nil
	}
	out := new(Instance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceParameterSpec) DeepCopyInto(out *InstanceParameterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceParameterSpec.
func (in *InstanceParameterSpec) DeepCopy() *InstanceParameterSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceParameterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedName) DeepCopyInto(out *NamespacedName) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedName.
func (in *NamespacedName) DeepCopy() *NamespacedName {
	if in == nil {
		return nil
	}
	out := new(NamespacedName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformConfig) DeepCopyInto(out *PlatformConfig) {
	*out = *in
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformConfig.
func (in *PlatformConfig) DeepCopy() *PlatformConfig {
	if in == nil {
		return nil
	}
	out := new(PlatformConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderIcon) DeepCopyInto(out *ProviderIcon) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderIcon.
func (in *ProviderIcon) DeepCopy() *ProviderIcon {
	if in == nil {
		return nil
	}
	out := new(ProviderIcon)
	in.DeepCopyInto(out)
	return out
}
